---
title: "Gateway to Research Data Collection"
author: "Joseph Wilson"
date: "18/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import_packages}
library(jsonlite)
library(httr)
library(tidyverse)
library(rvest)
library(janitor)
library(magrittr)
library(logr)
library(progress)
```

# Grant Data

```{r import_and_clean_base_project_df}
project_df <- read.csv("../data/projectsearch-data.csv")

# clean column names up
project_df %<>%
  clean_names() %>% 
  rename(
    pi_orcid_id = pi_orcid_i_d ,
    student_orcid_id = student_orcid_i_d,
  )

# add abstract column
project_df %<>% 
  add_column(abstract = NA) %>% 
  mutate(across(abstract, as.character))

# Change blank strings to NAs
project_df %<>% 
  mutate_if(is.character, list(~na_if(.,"")))

# Combine PI and Student columns and drop
project_df %<>% 
  mutate(
    pi_surname = coalesce(pi_surname, student_surname),
    pi_first_name = coalesce(pi_first_name, student_first_name),
    pi_other_names = coalesce(pi_other_names, student_other_names),
    pi_orcid_id = coalesce(pi_orcid_id, student_orcid_id),
  ) %>%
  select(!c(
    student_surname,
    student_first_name,
    student_other_names,
    student_orcid_id
  ))

```

```{r test_project_info_collection}
i = 4185

# extract the project URL
project_url <- project_df$gtr_project_url[i]

# extract the project reference number for use in the other dataframes
project_ref <- project_df$project_reference[i]

# check and correct for faulty urls by rebuilding them
project_type <- project_df$project_category[i]

if (project_type == "Studentship") {
  # build correct Studentship URL with project ref number
  project_url <- paste("https://gtr.ukri.org/projects?ref=studentship-", project_ref, collapse = "", sep = "")
  # save corrected URL in dataframe
  project_df$gtr_project_url[i] <- project_url
} else {
  # build correct Studentship URL with project ref number
  project_url <- paste("https://gtr.ukri.org/projects?ref=", project_ref, collapse = "", sep = "")
  # save corrected URL in dataframe
  project_df$gtr_project_url[i] <- project_url
}

start_time <- Sys.time()

project_info <- fromJSON(
  project_url,
  simplifyDataFrame = TRUE,
  flatten = TRUE)

end_time <- Sys.time()

message(end_time - start_time)
```

```{r define_function}
# define the data collection function
get_project_info <- function(i) {
  tryCatch(
    {
      # extract the project URL
      project_url <<- project_df$gtr_project_url[i]
      
      # extract the project reference number for use in the other dataframes
      project_ref <<- project_df$project_reference[i]
      
      # check and correct for faulty urls by rebuilding them
      project_type <<- project_df$project_category[i]
      
      if (project_type == "Studentship") {
        # build correct Studentship URL with project ref number
        project_url <<- paste(
          "https://gtr.ukri.org/projects?ref=studentship-", 
          project_ref, 
          collapse = "", 
          sep = ""
        )
        # save corrected URL in dataframe
        project_df$gtr_project_url[i] <- project_url
      } else {
        # build correct Studentship URL with project ref number
        project_url <<- paste(
          "https://gtr.ukri.org/projects?ref=", 
          project_ref, 
          collapse = "", 
          sep = ""
        )
        # save corrected URL in dataframe
        project_df$gtr_project_url[i] <<- project_url
      }
      
      start_time <<- Sys.time()

      project_info <<- fromJSON(
        project_url,
        simplifyDataFrame = TRUE,
        flatten = TRUE)
      
      end_time <<- Sys.time()
      
      # calculate wait time
      wait_time <<- end_time - start_time
      
      # extract abstract and assign it to the relevant cell
      abstract <<- project_info$projectOverview$projectComposition$project$abstractText
      project_df$abstract[i] <<- abstract
      
      # add to person df
      personRole <<- as_tibble(project_info$projectOverview$projectComposition$personRole) %>% 
        add_column(project.ref = project_ref, .before = 1)
      
      person_df <<- person_df %>% bind_rows(personRole)
      
      # add to organisation df
      organisationRole <- as_tibble(project_info$projectOverview$projectComposition$organisationRole) %>% 
        add_column(project.ref = project_ref, .before = 1)
      
      organisation_df <<- organisation_df %>% bind_rows(organisationRole)
      
      # add to research_subject df
      researchSubject <- as_tibble(project_info$projectOverview$projectComposition$project$researchSubject) %>% 
        add_column(project.ref = project_ref, .before = 1)
      
      subject_df <<- subject_df %>% bind_rows(researchSubject)
      
      # add to research_topic df
      researchTopic <- as_tibble(project_info$projectOverview$projectComposition$project$researchTopic) %>% 
        add_column(project.ref = project_ref, .before = 1)
      
      topic_df <<- topic_df %>% bind_rows(researchTopic)
      
      # log successful data collection
      log_print(
        str_glue("Data collected from {project_url} successfully in {round(as.numeric(wait_time),6)} seconds"), 
        console = FALSE
      )
      
    },
    error=function(cond) {
      # log the error in the dataframe for collection later
      error_project_df <<- error_project_df %>% add_row(i = i, url = project_url)
      
      error_time <- format(Sys.time(), "%H:%M:%S")
      # log unsuccessful data collection with details of issue
      log_print(str_glue("Data collection from {project_url} at {error_time} failed: \n {cond} \n Waiting 5 minutes before resuming."))
      
      # set the wait time to 5 minutes.
      wait_time <<- 300
    },
    finally = {
      # update progress bar to monitor process
      prog_bar$tick()
      
      # wait the calculated time
      Sys.sleep(wait_time)
    }
  )
}
```

```{r test_data_collection_functionality}
# init auxiliary df lists which will be later combined to make the auxiliary dfs
person_df <- tibble()
organisation_df <- tibble()
subject_df <- tibble()
topic_df <- tibble()

# init error capture dataframe
error_project_df <- tibble(
  i = numeric(),
  url = character(),
)

# init progress bar
prog_bar_len <- 100
prog_bar <- progress_bar$new(format = "[:bar] :current/:total -:percent complete - :elapsedfull - eta = :eta",
                             total = prog_bar_len)

# start logging
log_file_dest <- paste0("../logs/TESTRUN_", format(Sys.time(), "%Y%m%d_%H%M%S_"), "log.log")
log_file <- log_open(log_file_dest, logdir = FALSE)

for (i in 1:prog_bar_len) {
  get_project_info(i)
}

person_df_mutated <- person_df %>% 
  rowwise() %>% 
  mutate(role = paste(pull(role), collapse = ","))

organisation_df_mutated <- organisation_df %>% 
  rowwise() %>% 
  mutate(role = paste(pull(role), collapse = ","))

person_df_mutated
log_print("person_df.csv saved")

organisation_df_mutated
log_print("organisation_df.csv saved")

subject_df
log_print("subject_df.csv saved")

topic_df
log_print("topic_df.csv saved")

project_df
log_print("project_df.csv saved")

# Close log
log_close()
```

```{r collect_data}
# init auxiliary df lists which will be later combined to make the auxiliary dfs
person_df <- tibble()
organisation_df <- tibble()
subject_df <- tibble()
topic_df <- tibble()

# init error capture dataframe
error_project_df <- tibble(
  i = numeric(),
  url = character(),
)

# init progress bar
prog_bar_len <- dim(project_df)[1]
prog_bar <- progress_bar$new(format = "[:bar] :current/:total -:percent complete - :elapsedfull - eta = :eta",
                             total = prog_bar_len)

# start logging
log_file_dest <- paste0("../logs/", format(Sys.time(), "%Y%m%d_%H%M%S_"), "log.log")
log_file <- log_open(log_file_dest, logdir = FALSE)

for (i in 1:prog_bar_len) {
  get_project_info(i)
}

person_df_mutated <- person_df %>% 
  rowwise() %>% 
  mutate(role = paste(pull(role), collapse = ","))

organisation_df_mutated <- organisation_df %>% 
  rowwise() %>% 
  mutate(role = paste(pull(role), collapse = ","))

# save and log data frames
person_df_mutated %>% write.csv("../data/person_df.csv")
log_print("person_df.csv saved")

organisation_df_mutated %>% write.csv("../data/organisation_df.csv")
log_print("organisation_df.csv saved")

subject_df %>% write.csv("../data/subject_df.csv")
log_print("subject_df.csv saved")

topic_df %>% write.csv("../data/topic_df.csv")
log_print("topic_df.csv saved")

project_df %>% write.csv("../data/project_df.csv")
log_print("project_df.csv saved")

# Close log
log_close()

```

```{r errored projected redo}
# Pull the list of errorred projects row numbers
errorred_projects <- error_project_df$i
# Back up dataframe incase of an issue
ep_df_bkup <- error_project_df

# Empty error capture dataframe
error_project_df <- tibble(
  i = numeric(),
  url = character(),
)

# init progress bar
prog_bar_len <- length(errored_projects)
prog_bar <- progress_bar$new(format = "[:bar] :current/:total -:percent complete - :elapsedfull - eta = :eta",
                             total = prog_bar_len)

# start logging
log_file_dest <- paste0("../logs/", format(Sys.time(), "%Y%m%d_%H%M%S_"), "Errored_Project_Retry_log.log")
log_file <- log_open(log_file_dest, logdir = FALSE)

for (i in errored_projects) {
  get_project_info(i)
  # add extra sleep for safety
  Sys.sleep(5)
}

person_df_mutated <- person_df %>% 
  rowwise() %>% 
  mutate(role = paste(pull(role), collapse = ","))

organisation_df_mutated <- organisation_df %>% 
  rowwise() %>% 
  mutate(role = paste(pull(role), collapse = ","))

# save and log data frames
person_df_mutated %>% write.csv("../data/person_df.csv")
log_print("person_df.csv saved")

organisation_df_mutated %>% write.csv("../data/organisation_df.csv")
log_print("organisation_df.csv saved")

subject_df %>% write.csv("../data/subject_df.csv")
log_print("subject_df.csv saved")

topic_df %>% write.csv("../data/topic_df.csv")
log_print("topic_df.csv saved")

project_df %>% write.csv("../data/project_df.csv")
log_print("project_df.csv saved")

# Close log
log_close()

```


```{r view dataframe}
person_df_mutated
organisation_df_mutated
subject_df
topic_df
project_df
```




