---
title: "EPSRC Grant Funding Outcomes"
subtitle: "Grants on the Web Data Collection"
output:
  pdf_document: 
    number_sections: yes
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r package_install, echo=FALSE, message=FALSE}
# General-purpose data wrangling
library(tidyverse)  
# Parsing of HTML/XML files  
library(rvest)    
# String manipulation
library(stringr)
# Cleaning dataframe names
library(janitor)
# Logging
library(logr)
# Progress monitoring
library(progress)
```


```{r progress bar creation function}
init_bar <- function(bar_length){
  bar <- progress_bar$new(
    format = "[:bar] :current/:total -:percent complete - :elapsedfull - eta = :eta \n", 
    total = bar_length
  )
  return(bar)
}
```


# Themes

```{r set variables and functions}
# this function is more reliable than a plain read_html is less likely to result in an 400 http error.
get_html <- function(url){
  # set file location
  html_dest = '../data/temp_gow_html.html'
  
  start_time <- Sys.time()
  # download and read html from website
  download.file(paste("https://gow.epsrc.ukri.org/",url,sep = ""), destfile = html_dest, quiet = TRUE)
  end_time <- Sys.time()
  
  return(list(
      html = read_html(html_dest),
      wait = end_time - start_time
    ))
}
```

```{r}

# base theme url
base_url <- "NGBOListThemes.aspx"

# get html content from url
content <- get_html(base_url)$html

# parse HTML for list of hrefs
theme_href_list <- content %>%
  html_nodes(xpath = "//td/a") %>% 
  html_attr("href")

# parse HTML for list of theme names
theme_name_list <- content %>%
  html_nodes(xpath = "//td/a") %>% 
  html_text()

# drop last elements as blank
theme_href_list <- theme_href_list[1:12]
theme_name_list <- theme_name_list[1:12]

# Split in to challenge and capability themes
challenge_themes <- theme_name_list[1:5]
capability_themes <- theme_name_list[6:12]

# # extract theme names from urls and store them
# theme_list <- c()
#   
# for (url in theme_href_list) {
#   theme_name <- str_match(url, "Theme=(.*?)&")[2]
#   theme_list <- c(theme_list, theme_name)
# }
```

```{r init_tibble}
theme_df <- tibble(
  theme_name = character(),
  theme_type = character(),
  research_area = character(),
  grant_ref = character()
)
```

```{r grants}
# https://gow.epsrc.ukri.org/NGBOListThemeDrillDown.aspx?CapabilityTheme=Engineering&ItemId=Engineering

for (theme_url in theme_href_list) {
  # first get the equivalent theme name
  theme_name <- theme_name_list[which(theme_href_list == theme_url)[1]]
  
  # is the theme a challenge theme or a capability theme
  theme_type <- ifelse(theme_name %in% challenge_themes, 'Challenge', 'Capability')
  
  # then get the html page for the theme
  start_time <- Sys.time()
  theme_content <- get_html(theme_url)$html
  end_time <- Sys.time()
  # work out duration for response for polite requesting
  theme_wait <- end_time - start_time
  
  # parse HTML for list of research area urls
  area_href_list <- theme_content %>%
    html_nodes(xpath = "//td/a") %>% 
    html_attr("href")

  # parse HTML for list of research area names
  area_name_list <- theme_content %>%
    html_nodes(xpath = "//td/a") %>% 
    html_text()
  
  # wait for the response duration to be polite to the website
  Sys.sleep(theme_wait)
  
  for (area_url in area_href_list) {
    # first get the equivalent research area name
    area_name <- area_name_list[which(area_href_list == area_url)[1]]
    
    # get html content from website, timing the response time
    start_time <- Sys.time()
    area_content <- get_html(area_url)$html
    end_time <- Sys.time()
    
    # calculate the response time
    area_wait <- end_time - start_time
    
    # only need to parse the links so we can later extract the grant reference number
    grant_ref_list <- area_content %>%
      html_nodes(xpath = "//td/a") %>% 
      html_attr("title") %>% 
      unique()
    
    for (grant_ref in grant_ref_list) {
      theme_df <- theme_df %>% 
        add_row(
            theme_name = theme_name,
            theme_type = theme_type,
            research_area = area_name,
            grant_ref = grant_ref
        )
      
    }
    
    Sys.sleep(area_wait)
  }
  
  
}


```

```{r save_df}
theme_df %>% write.csv('../data/themes.csv')
```


# Panels

```{r define extraction functions}
extract_table <- function(html, css_selector, head_row = FALSE, log_on = TRUE){
  out <- tryCatch(
    {
      element <- html %>% 
        html_element(css_selector)
      
      if (length(element) > 0) {
        html_out <- element %>% html_table(header = head_row) %>% clean_names()
        
        if (log_on) {
          log_print(
            str_glue("Successfully extracted {css_selector} table"), 
            console = FALSE, 
            hide_notes = TRUE
          )
        }
      } else {
        html_out <- tibble()
        
        if (log_on) {
          log_print(
            str_glue("{css_selector} not detected."), 
            console = FALSE, 
            hide_notes = TRUE
          )
        }
      }
      
      html_out
      
    },
    error=function(cond){
      if (log_on) {
        log_print(
          str_glue("Error occured when extracting {css_selector} table. \n{cond}"), 
          console = FALSE, 
          hide_notes = TRUE
        )
      }
      return(tibble())
    }
  )
  return(out)
}

extract_elements <- function(html, css_selector, attr = "text", log_on = TRUE){
  out <- tryCatch(
    {
      element <- html %>% 
        html_element(css_selector)
      
      if (length(element) > 0) {
        if (attr == "text") {
          out <- element %>% 
            html_text(trim = TRUE) 
        } else {
          out <- element %>%
            html_attr(attr)
        }
        
        # Detect if logging is on for this function (on by default)
        if (log_on) {
          log_print(
            str_glue("Successfully extracted '{css_selector}' element's '{attr}' attributes"), 
            console = FALSE, 
            hide_notes = TRUE
          )
        }
        
      } else {
        out <- list()
        
        # Detect if logging is on for this function (on by default)
        if (log_on) {
          log_print(
            str_glue("'{css_selector}' element's '{attr}' attributes not detected."), 
            console = FALSE, 
            hide_notes = TRUE
          )
        }
      }
      # The trycatch returns the last expression so we need to ensure that it is returned
      out
    },
    error=function(cond){
      if (log_on) {
        log_print(
          str_glue("Error occured when extracting '{css_selector}' element's '{attr}' attributes.\n{cond}"), 
          console = FALSE,
          hide_notes = TRUE
        )
      }
      return(list())
    }
  )
  return(out)
}
```



```{r define addrow functions}
log_bind_row <- function(df, data, log_on = TRUE){
  # get variable names for logging
  df_name <- deparse(substitute(df))
  data_name <- deparse(substitute(data))
  # add row to data
  if (dim(data)[1] > 0) {
    df <- bind_rows(df, data %>% mutate(across(.fns = as.character)))
    
    if (log_on) {
      log_print(
        str_glue("Successfully updated {df_name} with {data_name} data"), 
        console = FALSE,
        hide_notes = TRUE
      )
    }
  }
  
  return(df)
}

```


```{r experimental_scaping}
test_dataframes <- list(
  panel_details_df = tibble(),
  panel_members_df = tibble(),
  funded_type1_bynum_df = tibble(),
  funded_type1_byvalue_df = tibble(),
  outlines_bynum_df = tibble(),
  outline_byvalue_df = tibble(),
  deferred_fellowships_grants_df = tibble(),
  approved_fellowships_grants_df = tibble(),
  sift_grants_bynum_df = tibble(),
  sift_grants_byvalue_df = tibble(),
  funded_type2_bynum_df = tibble(),
  funded_type2_byvalue_df = tibble(),
  panel_rank_links_df = tibble()
)

test_link <- "NGBOViewPanel.aspx?PanelId=1-4SSWIR"

log_on <- FALSE

# get panel html
panel <- get_html(test_link)

# extract general panel details
# general content: panel id - from link
panel_id <- str_match(test_link,"PanelId=(.*)")[2]

# general content: panel name (#lblPanelName) - from html
panel_name <- panel$html %>% html_element("#lblPanelName") %>% html_text()

# general content: panel date (#lblDateOfPanel) - from html
panel_date <- panel$html %>% html_element("#lblDateOfPanel") %>% html_text()

# general content: panel contact (#lblPanelContact) - from html
panel_contact <- panel$html %>% html_element("#lblPanelContact") %>% html_text()

# general content: panel page type - from link
panel_type <- paste(str_match(test_link,"([A-Z]*)View(.*?).aspx?")[2:3], collapse = '')

panel_details <- tibble(
  panel_id = panel_id,
  panel_name = panel_name,
  panel_date = panel_date,
  panel_contact = panel_contact,
  panel_type = panel_type,
)

test_dataframes$panel_details_df <- log_bind_row(test_dataframes$panel_details_df, panel_details, log_on = log_on)

# extract tables
#dgDetails
panel_members <- panel$html %>% 
  extract_table("#dgDetails", head_row = FALSE, log_on = log_on) %>% 
  mutate(panel_id = panel_id, panel_type = panel_type)

test_dataframes$panel_members_df <- log_bind_row(test_dataframes$panel_members_df, panel_members, log_on = log_on)

#dgFullByNum
funded_type1_bynum <- panel$html %>% 
  extract_table("#dgFullByNum", head_row = TRUE, log_on = log_on) %>% 
  mutate(panel_id = panel_id, panel_type = panel_type)

test_dataframes$funded_type1_bynum_df <- log_bind_row(test_dataframes$funded_type1_bynum_df, funded_type1_bynum, log_on = log_on)

#dgFullByValue
funded_type1_byvalue <- panel$html %>% 
  extract_table("#dgFullByValue", head_row = TRUE, log_on = log_on) %>% 
  mutate(panel_id = panel_id, panel_type = panel_type)
  
test_dataframes$funded_type1_byvalue_df <- log_bind_row(test_dataframes$funded_type1_byvalue_df, funded_type1_byvalue, log_on = log_on)

#dgOutlineByNumber
outlines_bynum <- panel$html %>% 
  extract_table("#dgOutlineByNumber", head_row = TRUE, log_on = log_on) %>% 
  mutate(panel_id = panel_id, panel_type = panel_type)

test_dataframes$outlines_bynum_df <- log_bind_row(test_dataframes$outlines_bynum_df, outlines_bynum, log_on = log_on)

#dgOutlineByValue
outline_byvalue <- panel$html %>% 
  extract_table("#dgOutlineByValue", log_on = log_on) %>% 
  mutate(panel_id = panel_id, panel_type = panel_type)

test_dataframes$outline_byvalue_df <- log_bind_row(test_dataframes$outline_byvalue_df, outline_byvalue, log_on = log_on)

#dgDeferredGrants span
deferred_fellowships_grants <- panel$html %>% 
  extract_elements("#dgDeferredGrants span", log_on = log_on) %>% 
  tibble(grant_ref = .) %>% 
  filter(grant_ref != "") %>% 
  mutate(panel_id = panel_id, panel_type = panel_type)

test_dataframes$deferred_fellowships_grants_df <- log_bind_row(test_dataframes$deferred_fellowships_grants_df, deferred_fellowships_grants, log_on = log_on)

#dgGrants
approved_fellowships_grants <- panel$html %>% 
  extract_table("#dgGrants", log_on = log_on) %>% 
  mutate(panel_id = panel_id, panel_type = panel_type)

test_dataframes$approved_fellowships_grants_df <- log_bind_row(test_dataframes$approved_fellowships_grants_df, approved_fellowships_grants, log_on = log_on)

#dgSiftByNumber
sift_grants_bynum <- panel$html %>% 
  extract_table("#dgSiftByNum", head_row = TRUE, log_on = log_on) %>% 
  mutate(panel_id = panel_id, panel_type = panel_type)

test_dataframes$sift_grants_bynum_df <- log_bind_row(test_dataframes$sift_grants_bynum_df, sift_grants_bynum, log_on = log_on)

#dgSiftByValue
sift_grants_byvalue <- panel$html %>% 
  extract_table("#dgSiftByValue", head_row = TRUE, log_on = log_on) %>% 
  mutate(panel_id = panel_id, panel_type = panel_type)

test_dataframes$sift_grants_byvalue_df <- log_bind_row(test_dataframes$sift_grants_byvalue_df, sift_grants_byvalue, log_on = log_on)

#dgPanelByNum
funded_type2_bynum <- panel$html %>% 
  extract_table("#dgPanelByNum", head_row = TRUE, log_on = log_on) %>% 
  mutate(panel_id = panel_id, panel_type = panel_type)

test_dataframes$funded_type2_bynum_df <- log_bind_row(test_dataframes$funded_type2_bynum_df, funded_type2_bynum, log_on = log_on)

#dgPanelByValue
funded_type2_byvalue <- panel$html %>% 
  extract_table("#dgPanelByValue", head_row = TRUE, log_on = log_on) %>% 
  mutate(panel_id = panel_id, panel_type = panel_type)

test_dataframes$funded_type2_byvalue_df <- log_bind_row(test_dataframes$funded_type2_byvalue_df, funded_type2_byvalue, log_on = log_on)

  # pull links
#pnlContent a
panel_rank_links <-  panel$html %>% 
  extract_elements("#pnlContent a", attr = "href", log_on = log_on) %>% 
  tibble(href = .) %>% 
  filter(str_detect(href, "NGBOViewPanelROL.aspx?")) %>% 
  mutate(panel_id = panel_id, panel_type = panel_type)

test_dataframes$panel_rank_links_df <- log_bind_row(test_dataframes$panel_rank_links_df, panel_rank_links, log_on = log_on)

```

```{r func_def_panel_data}
# dataframes <- list(
#   panel_details_df = tibble(),
#   panel_members_df = tibble(),
#   funded_type1_bynum_df = tibble(),
#   funded_type1_byvalue_df = tibble(),
#   outlines_bynum_df = tibble(),
#   outline_byvalue_df = tibble(),
#   deferred_fellowships_grants_df = tibble(),
#   approved_fellowships_grants_df = tibble(),
#   sift_grants_bynum_df = tibble(),
#   sift_grants_byvalue_df = tibble(),
#   funded_type2_bynum_df = tibble(),
#   funded_type2_byvalue_df = tibble(),
#   panel_rank_links_df = tibble()
# )
# 
# error_panel_links <- c()

sweet_get_panel_data <- function(link, dataframes = dataframes, log_on = TRUE, errors = c()){
  # wrapped function for collecting data from panel
  # get panel html
  panel <- get_html(link)
  
  # extract general panel details
  # general content: panel id - from link
  panel_id <- str_match(link,"PanelId=(.*)")[2]
  
  # general content: panel name (#lblPanelName) - from html
  panel_name <- panel$html %>% html_element("#lblPanelName") %>% html_text()
  
  # general content: panel date (#lblDateOfPanel) - from html
  panel_date <- panel$html %>% html_element("#lblDateOfPanel") %>% html_text()
  
  # general content: panel contact (#lblPanelContact) - from html
  panel_contact <- panel$html %>% html_element("#lblPanelContact") %>% html_text()
  
  # general content: panel page type - from link
  panel_type <- paste(str_match(link,"([A-Z]*)View(.*?).aspx?")[2:3], collapse = '')
  
  panel_details <- tibble(
    panel_id = panel_id,
    panel_name = panel_name,
    panel_date = panel_date,
    panel_contact = panel_contact,
    panel_type = panel_type,
  )
  
  if (log_on) {
    log_print(
      str_glue("Successfully extracted panel details"), 
      console = FALSE, 
      hide_notes = TRUE
    )
  }
  
  dataframes$panel_details_df <- log_bind_row(dataframes$panel_details_df, panel_details, log_on = log_on)
  
  # extract tables
  #dgDetails
  panel_members <- panel$html %>% 
    extract_table("#dgDetails", head_row = FALSE, log_on = log_on) %>% 
    mutate(panel_id = panel_id, panel_type = panel_type)
  
  dataframes$panel_members_df <- log_bind_row(dataframes$panel_members_df, panel_members, log_on = log_on)
  
  #dgFullByNum
  funded_type1_bynum <- panel$html %>% 
    extract_table("#dgFullByNum", head_row = TRUE, log_on = log_on) %>% 
    mutate(panel_id = panel_id, panel_type = panel_type)
  
  dataframes$funded_type1_bynum_df <- log_bind_row(dataframes$funded_type1_bynum_df, funded_type1_bynum, log_on = log_on)

  #dgFullByValue
  funded_type1_byvalue <- panel$html %>% 
    extract_table("#dgFullByValue", head_row = TRUE, log_on = log_on) %>% 
    mutate(panel_id = panel_id, panel_type = panel_type)
    
  dataframes$funded_type1_byvalue_df <- log_bind_row(dataframes$funded_type1_byvalue_df, funded_type1_byvalue, log_on = log_on)
  
  #dgOutlineByNumber
  outlines_bynum <- panel$html %>% 
    extract_table("#dgOutlineByNumber", head_row = TRUE, log_on = log_on) %>% 
    mutate(panel_id = panel_id, panel_type = panel_type)
  
  dataframes$outlines_bynum_df <- log_bind_row(dataframes$outlines_bynum_df, outlines_bynum, log_on = log_on)
  
  #dgOutlineByValue
  outline_byvalue <- panel$html %>% 
    extract_table("#dgOutlineByValue", log_on = log_on) %>% 
    mutate(panel_id = panel_id, panel_type = panel_type)
  
  dataframes$outline_byvalue_df <- log_bind_row(dataframes$outline_byvalue_df, outline_byvalue, log_on = log_on)
  
  #dgDeferredGrants span
  deferred_fellowships_grants <- panel$html %>% 
    extract_elements("#dgDeferredGrants span", log_on = log_on) %>% 
    tibble(grant_ref = .) %>% 
    filter(grant_ref != "") %>% 
    mutate(panel_id = panel_id, panel_type = panel_type)
  
  dataframes$deferred_fellowships_grants_df <- log_bind_row(dataframes$deferred_fellowships_grants_df, deferred_fellowships_grants, log_on = log_on)
  
  #dgGrants
  approved_fellowships_grants <- panel$html %>% 
    extract_table("#dgGrants", log_on = log_on) %>% 
    mutate(panel_id = panel_id, panel_type = panel_type)
  
  dataframes$approved_fellowships_grants_df <- log_bind_row(dataframes$approved_fellowships_grants_df, approved_fellowships_grants, log_on = log_on)
  
  #dgSiftByNum
  sift_grants_bynum <- panel$html %>% 
    extract_table("#dgSiftByNum", head_row = TRUE, log_on = log_on) %>% 
    mutate(panel_id = panel_id, panel_type = panel_type)
  
  dataframes$sift_grants_bynum_df <- log_bind_row(dataframes$sift_grants_bynum_df, sift_grants_bynum, log_on = log_on)
  
  #dgSiftByValue
  sift_grants_byvalue <- panel$html %>% 
    extract_table("#dgSiftByValue", head_row = TRUE, log_on = log_on) %>% 
    mutate(panel_id = panel_id, panel_type = panel_type)
  
  dataframes$sift_grants_byvalue_df <- log_bind_row(dataframes$sift_grants_byvalue_df, sift_grants_byvalue, log_on = log_on)
  
  #dgPanelByNum
  funded_type2_bynum <- panel$html %>% 
    extract_table("#dgPanelByNum", head_row = TRUE, log_on = log_on) %>% 
    mutate(panel_id = panel_id, panel_type = panel_type)
  
  dataframes$funded_type2_bynum_df <- log_bind_row(dataframes$funded_type2_bynum_df, funded_type2_bynum, log_on = log_on)
  
  #dgPanelByValue
  funded_type2_byvalue <- panel$html %>% 
    extract_table("#dgPanelByValue", head_row = TRUE, log_on = log_on) %>% 
    mutate(panel_id = panel_id, panel_type = panel_type)
  
  dataframes$funded_type2_byvalue_df <- log_bind_row(dataframes$funded_type2_byvalue_df, funded_type2_byvalue, log_on = log_on)
  
    # pull links
  #pnlContent a
  panel_rank_links <-  panel$html %>% 
    extract_elements("#pnlContent a", attr = "href", log_on = log_on) %>% 
    tibble(href = .) %>% 
#    filter(str_detect(href, "NGBOViewPanelROL.aspx?")) %>% # Commenting out to allow review of link incase this is not inclusive of all rank page links.
    mutate(panel_id = panel_id, panel_type = panel_type)
  
  dataframes$panel_rank_links_df <- log_bind_row(dataframes$panel_rank_links_df, panel_rank_links, log_on = log_on)
  
  # output the updated dataframes, the wait time, and the unchanged errors
  return(
    list(
      dataframes = dataframes,
      wait = panel$wait,
      errors = errors
    )
  )
}

get_panel_data <- function(link, dataframes = panel_dataframes, log_on = TRUE, errors = c()){
  # Error resistant wrapper function for the wrapped sweet_get_panel_data
  out <- tryCatch(
    {
      if (log_on) {
        log_print(
          str_glue("Starting data extraction from {link}."), 
          console = FALSE,
          hide_notes = TRUE
        )
      }
      sweet_get_panel_data(link, dataframes, log_on = log_on, errors = errors)
    },
    error = function(cond){
      new_errors <- c(errors, link)
      
      if (log_on) {
        log_print(
          str_glue(
          "Failed to extract data and update dataframes due to error.\nURL: {link}\n{cond}\nFailed links: \n{error_panel_links}"), 
          console = FALSE,
          hide_notes = TRUE
        )
      }
      # set a wait time
      wait_time <- 15 #seconds
      
      # ensure that the dataframes are passed through without issue and unchanged
      return(
        list(
          dataframes = dataframes,
          wait = wait_time,
          errors = new_errors
        )
      )
    }
  )
  # wait
  Sys.sleep(out$wait)
  # update progress bar if it has been created and has not finished
  if (exists('pb')){
    if (!pb$finished) {
    pb$tick()
    }
  }
  if (log_on) {
    log_print(
      str_glue("Finished data extraction from {link}."), 
      console = FALSE,
      hide_notes = FALSE
    )
  }
  return(out)
  
}
```

```{r}
# Open log
lf <- log_open(paste0("../logs/gow/test_log_", format(Sys.time(), "%Y%m%d_%H%M%S"), ".log"), logdir = FALSE)

get_panel_data("NGBOViewPanel.aspx?PanelId=1-4SSWIR", dataframes = dataframes, log_on = TRUE, errors = error_panel_links)

# Close log
log_close()

# View results
writeLines(readLines(lf))
```



```{r create complete panel link list}
# The complete html results list of panels between 01/01/2006 and 13/06/2021 has been downloaded and saved
panel_lst_content <- read_html('../data/gow_panels-01012006_to_13062021.html')

# parse HTML for list of hrefs
panel_href_list <- panel_lst_content %>%
  html_elements('#dgDetails a:nth-child(1)') %>% 
  html_attr('href')
```

```{r}
bar_len <- length(panel_href_list)
pb <- init_bar(bar_len)

# Run through the progress bar
# for (i in 1:bar_len) {
#   if (!pb$finished) {
#     pb$tick()
#   }
# }


# for (link in panel_href_list) {
#   
# }

```


```{r sample_test_run}
sample_dataframes <- list(
  panel_details_df = tibble(),
  panel_members_df = tibble(),
  funded_type1_bynum_df = tibble(),
  funded_type1_byvalue_df = tibble(),
  outlines_bynum_df = tibble(),
  outline_byvalue_df = tibble(),
  deferred_fellowships_grants_df = tibble(),
  approved_fellowships_grants_df = tibble(),
  sift_grants_bynum_df = tibble(),
  sift_grants_byvalue_df = tibble(),
  funded_type2_bynum_df = tibble(),
  funded_type2_byvalue_df = tibble(),
  panel_rank_links_df = tibble()
)

sample_error_panel_links <- c()
# Open log
lf <- log_open(paste0("../logs/gow/sample_run_", format(Sys.time(), "%Y%m%d_%H%M%S"), ".log"), logdir = FALSE)

# Create a sample list of panel_links
panel_links <- tibble(link = panel_href_list) %>% mutate(group = apply(str_match(panel_href_list,"([A-Z]*)View(.*?).aspx?")[,2:3], 1,paste, collapse = ''))

sample_list <- panel_links %>% group_by(group) %>% slice_sample(n = 10) %>% pull(link)

bar_len <- length(sample_list)
pb <- init_bar(bar_len)

for (link in sample_list) {
  panel_data_output <- get_panel_data(link, dataframes = sample_dataframes, log_on = TRUE, errors = sample_error_panel_links)
  
  sample_dataframes <- panel_data_output$dataframes
  
  sample_error_panel_links <- panel_data_output$errors
  
  #browseURL(paste("https://gow.epsrc.ukri.org/", link,sep = ''))
}

# Close log
log_close()

# view failed links
sample_error_panel_links

# view dataframe
sample_dataframes
```

```{r full run code}
dataframes <- list(
  panel_details_df = tibble(),
  panel_members_df = tibble(),
  funded_type1_bynum_df = tibble(),
  funded_type1_byvalue_df = tibble(),
  outlines_bynum_df = tibble(),
  outline_byvalue_df = tibble(),
  deferred_fellowships_grants_df = tibble(),
  approved_fellowships_grants_df = tibble(),
  sift_grants_bynum_df = tibble(),
  sift_grants_byvalue_df = tibble(),
  funded_type2_bynum_df = tibble(),
  funded_type2_byvalue_df = tibble(),
  panel_rank_links_df = tibble()
)

error_panel_links <- c()

# Open log
lf <- log_open(paste0("../logs/gow/full_run_", format(Sys.time(), "%Y%m%d_%H%M%S"), ".log"), logdir = FALSE)

# init progress bar
bar_len <- length(panel_href_list)
pb <- init_bar(bar_len)

for (link in panel_href_list) {
  panel_data_output <- get_panel_data(link, dataframes = dataframes, log_on = TRUE, errors = error_panel_links)
  
  dataframes <- panel_data_output$dataframes
  
  error_panel_links <- panel_data_output$errors
  
  #browseURL(paste("https://gow.epsrc.ukri.org/", link,sep = ''))
}

# Close log
log_close()

# view failed links
error_panel_links

# view dataframe
dataframes
```

```{r logging testing and debugging playground}
# Open log
lf <- log_open(paste0("../logs/gow/test_log_", format(Sys.time(), "%Y%m%d_%H%M%S"), ".log"), logdir = FALSE)

# Send message to log  
message = str_glue("Log is being written  to {lf}")
log_print("Test", console = FALSE, hide_notes = TRUE)

log_print(str_glue("Log is being written  to {lf}"), console = FALSE, hide_notes = TRUE)

log_print(message, console = FALSE, hide_notes = TRUE)

# Close log
log_close()

# View results
writeLines(readLines(lf))
```

```{r save dataframes}
saved_dataframes <- dataframes
save_path <- "../data/panel_dataframes/"

for (dfname in saved_dataframes %>% names()) {
  path <- paste0(save_path,dfname,".csv")
  saved_dataframes[[dfname]] %>% write_csv(file = path)
}
```


```{r filter links}
dataframes$panel_rank_links_df <- dataframes$panel_rank_links_df %>% 
  filter(str_detect(href, pattern = "ViewPanelROL.aspx"))

dataframes$panel_ranked_grants_df <- tibble()

bar_len <- dim(dataframes$panel_rank_links_df)[1]
# bar_len <- 100

for (i in 1:bar_len) {
  link <- dataframes$panel_rank_links_df$href[i]
  
  panel_id <- dataframes$panel_rank_links_df$panel_id[i]
  
  panel_type <- dataframes$panel_rank_links_df$panel_type[i]
  
  html <- get_html(link)
  
  grants <- extract_table(html, "#dgGrants", head_row = TRUE, log_on = log_on) %>% 
      mutate(panel_id = panel_id, panel_type = panel_type)
  
  # If there is a grants table and a deffered grant table, the deffered grants 
  # table will have no head
  if (dim(grants)[1] > 0) {
    defferred_grants <- extract_table(html, "#dgDeferredGrants", head_row = FALSE, log_on = log_on)
    
    new_colnames <- grants %>% colnames()
    
    defferred_grants <- defferred_grants %>% `colnames<-`(new_colnames)
  } else {
    defferred_grants <- extract_table(html, "#dgDeferredGrants", head_row = TRUE, log_on = log_on)
  }
  
  defferred_grants <- defferred_grants %>% 
      mutate(panel_id = panel_id, panel_type = panel_type)
  
  # Quickly view pages for CSS selector review
  # browseURL(paste("https://gow.epsrc.ukri.org/", link,sep = ''))
  
  
  dataframes$panel_ranked_grants_df <-dataframes$panel_ranked_grants_df %>% 
    log_bind_row(grants, log_on = log_on) %>% 
    log_bind_row(defferred_grants, log_on = log_on)
}
```

```{r}
test <- tibble(
  x1 = character(),
  x2 = character(),
  x3 = character(),
)

test %>% colnames()

new_colnames <- c("a","b","c")

test <- `colnames<-`(test, new_colnames)

test %>% colnames()
```

