[1] "Error in open.connection(con, \"rb\") : \n  Timeout was reached: [gtr.ukri.org:443] Operation timed out after 10004 milliseconds with 0 out of 0 bytes received\n"

[1] "Error in write.table(., \"../data/person_df.csv\", col.names = NA, sep = \",\",  : \n  unimplemented type 'list' in 'EncodeElement'\n"

[1] "Error in write.table(., \"../data/organisation_df.csv\", col.names = NA,  : \n  unimplemented type 'list' in 'EncodeElement'\n"

